### ISSUE TITLE
FUNCTIONALITY upSet plot contains an extra blank page  

### ISSUE THREAD

**Issue by fmaguire** [ramadatta/CPgeneProfiler#10]
On the testdata the generated upSet plot seems to contain an extra blank page.

[upSetR.pdf](https://github.com/ramadatta/CPgeneProfiler/files/4914396/upSetR.pdf)

**Comment by ramadatta** [comment]
This issue has been fixed. The plot now appears properly without any blank pages. Please find the link: https://github.com/ramadatta/CPgeneProfiler/blob/master/testData_Output/6_UpsetR_Intersection_Plot/upset_plot.pdf
