### ISSUE TITLE
AUTOMATED TESTS: add specific test section of README

### ISSUE THREAD

**Issue by fmaguire** [ramadatta/CPgeneProfiler#11]
While there is testdata and the quickstart example includes it, you should have a specific "Testing" section in your README that runs the testdata and describes the expected outcome. 

Ideally this would include automating this testing process (e.g. Continuous Integration).

**Comment by ramadatta** [comment]
We agree with the reviewer's comment on having testing section. In accordance to that, we now have “[Working with testData](https://github.com/ramadatta/CPgeneProfiler#working-with-testdata)” section which give details of each command and displays the expected outcome.

But given the time constraints, we could not automate the testing process. We will surely consider to do this upcoming versions of the package.
