### ISSUE TITLE
FUNCTIONALITY Splitting single function into individual functions would greatly improve utility

### ISSUE THREAD

**Issue by fmaguire** [ramadatta/CPgeneProfiler#12]
If there were more granularity than just one master function taking in the fasta+db and generating all the plots this package would improve the utility of this package.  By having the entire program/package one large program only users with the exact same use-case as you will benefit from your work.  If the package was split up into several different functions it would make it a lot more flexible.

Specifically, it is worth creating separate documented functions/APIs for each summary/visualisation/analysis with their own parameters.  For example, a function generating the upset plot could have parameters to just generate the plot for specific CP genes/families.  Similarly for other visualisations/summaries even the BLAST+parsing as a separate function would make it easier for users to tweak the BLAST parameters/change the specifics of the homology search.

**Comment by ramadatta** [comment]
We completely agree with reviewer’s comment on splitting single function to multiple to improve utility. `CPgeneProfiler` now has separate documented functions such as  `cpblast`, `filt_blast` which deals NCBI BLAST tool results and other visualization commands such as `cpprofile`, `plot_conlen`, `upsetR`. For all these functions, users can now tweak the parameters such as percent identity, alignment coverage, various plot sizes and colors. The [example usage](https://github.com/ramadatta/CPgeneProfiler#example-usage) section details each of these functions.

But given the time constraints, we could not specifically create a upset plot function for plotting specific CP gene/families. We surely consider to make this available in the upcoming versions of the package.
