### ISSUE TITLE
COMMUNITY GUIDELINES: need added

### ISSUE THREAD

**Issue by fmaguire** [ramadatta/CPgeneProfiler#13]
`Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support`

**Comment by ramadatta** [comment]
This issue has been fixed. We have now added community guidelines in our README page. This would help users understand on how to contribute, support and report any issues with software. Please find the link here: https://github.com/ramadatta/CPgeneProfiler#community-guidelines
