### ISSUE TITLE
STATEMENT OF NEED: paper needs to explain WHY all the plots are useful for CP surveillance

### ISSUE THREAD

**Issue by fmaguire** [ramadatta/CPgeneProfiler#17]
Need to explain the utility of contig length distribution analysis, co-carriage sets, and so on.

What specifically are these useful for in surveillance/profiling of CP genes? e.g. plasmid/MGE identification etc.

**Comment by ramadatta** [comment]
We agree with reviewer on this. In the updated manuscript we have elaborated the usefulness of each of the utility in relation to Carbapenemase (CP) gene analysis.
