### ISSUE TITLE
FUNCTIONALITY: Blastn thresholds for CP gene identification

### ISSUE THREAD

**Issue by boasvdp** [ramadatta/CPgeneProfiler#23]
The threshold for gene identification (if I understood correctly) is now an e-value score of 1e-6, and then selecting the best hit at a location. Other tools usually employ thresholds based on % nucleotide identity and % coverage, which is also a lot clearer for non-bioinformaticians.

Adding an option which can filter based on nucleotide identity or coverage (or at least reporting these clearly) would improve the tool

**Comment by boasvdp** [comment]
Upon closer inspection, I see that the filtering step excludes all hits that have less than 100% nucleotide identity and coverage. Although most common CP genes will be identified using this approach, one would expect false positives if genes are only partially assembled or new alleles are found. Being able to manage the thresholds would improve sensitivity

**Comment by ramadatta** [comment]
We agree with reviewer’s comment on this. The rewritten package now has commands such as `filt_blast`, `cocarriage`, `plot_conlen`, `upsetR_plot`. All these commands now has an option to filter based on `cpgpident` (nucleotide identity) and `cpgcov` (coverage) in the interest of the user. The default settings have been documented for each of these commands. Please find the [example usage](https://github.com/ramadatta/CPgeneProfiler#example-usage).
