### ISSUE TITLE
DOCUMENTATION: Default blastn settings are not indicated

### ISSUE THREAD

**Issue by boasvdp** [ramadatta/CPgeneProfiler#25]
CPgeneProfiler currently only looks for exact matches of CP genes (100% nucleotide identity, 100% coverage), which is not clear from the documentation.

**Comment by ramadatta** [comment]
We agree with the reviewer. The default parameters are mentioned in the documentation now. Users can now tweak the alignment coverage and percentage identity parameters while running `filt_blast` and `cocarriage` commands. Please find the details in the [example usage](https://github.com/ramadatta/CPgeneProfiler#example-usage) section.
