### ISSUE TITLE
DESCRIPTION file metadata incomplete

### ISSUE THREAD

**Issue by fmaguire** [ramadatta/CPgeneProfiler#5]
Please add the authorship/ORCID information etc to the R `DESCRIPTION` metadata file.

Currently looks like it is just placeholder metadata.

**Comment by ramadatta** [comment]
This issue has been fixed. DESCRIPTION metadata file now has authorship and relevant information. Please find the link here: https://github.com/ramadatta/CPgeneProfiler/blob/master/DESCRIPTION
