### ISSUE TITLE
INSTALLATION: Add R dependencies to R package so they are installed automatically

### ISSUE THREAD

**Issue by fmaguire** [ramadatta/CPgeneProfiler#7]
Please add the R package dependencies to the DESCRIPTION e.g. dplyr, tidyverse, UpSetR etc so they are automatically installed when the user runs `devtools::install_github("ramadatta/CPgeneProfiler")`

Optional: consider making a bioconda package (conda isn't exclusively python and there are a ton of non-python bioinformatics tools within bioconda now) that will install the tool AND the external BLAST+ dependency: the bioconda [docs](https://bioconda.github.io/contributor/index.html) and a [simple R package that already exists](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/r-rBLAST/meta.yaml) can be used as a template.

**Comment by ramadatta** [comment]
We agree with reviewer's comment. These issues have been fixed. 

R package dependencies are added to [DESCRIPTION](https://github.com/ramadatta/CPgeneProfiler/blob/master/DESCRIPTION) file. We are hopeful that this would ensure smooth installation of the package using devtools.

Additionally, in the README page under the [Requirements](https://github.com/ramadatta/CPgeneProfiler#requirements) section, we have provided the R commands to install relevant dependencies. 

 At this juncture, in view of submission time lines, we could not readily come up with bioconda package. But, we will surely consider making a bioconda package with all the dependencies in the upcoming versions of the package.
