### ISSUE TITLE
FUNCTIONALITY No assembly name axes labels in heatmap

### ISSUE THREAD

**Issue by fmaguire** [ramadatta/CPgeneProfiler#9]
When run on test data the generated heatmap doesn't contain assembly name axes labels. See example here:
![CPgeneProfile](https://user-images.githubusercontent.com/1698629/87339484-111c1d00-c51d-11ea-99ed-7cdd072c6835.png)

Without this the comparison utility of the heatmap is limited.

The colorbar label should be more specific than "value"

**Comment by ramadatta** [comment]
This issue has been fixed now. The CP gene profile [output plot](https://github.com/ramadatta/CPgeneProfiler/blob/master/testData_Output/3_CP_Gene_Profile/CPgeneProfile.png) now has genome assembly names. The color label is also now reset to “Gene Count”.
